---
- name: Become block
  block:
    - name: Install required packages
      apt:
        name: '{{ msft_packages_base | union(msft_packages_additional) | unique }}'
        state: present
        update_cache: true
      register: installed_package
      until: installed_package is succeeded

    - name: Install repository defenition from the internet
      apt:
        deb: '{{ msft_repo_deb_url }}'

    - name: Add universe repository
      apt_repository:
        repo: '{{ universe_repo_default }}'
        validate_certs: true
  become: true
